# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 790f4f16632948f8e8e79920f45d8db99142fa91faa4121bea87f681811bed7b686c3537d79621f7704519c7c705124da5262869cb8a9cf79700e936dbbff91e

test:
  secret_key_base: cc095ad4e6d31b846ca391a10b86a355393751dfa21472b8781747aa8cc83dd60ec23337cc34e71c7eaa953e4d264bd0a297336e4104c8ac755655825b013fb5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
